name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # -----
    # actions/setup-python
    # https://github.com/actions/setup-python
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5

    - name: Generate coverage report
      run: |
#        export PORT='8080'
#        export LINE_CHANNEL_ACCESS_TOKEN=${{secrets.LINE_CHANNEL_ACCESS_TOKEN}}
#        export LINE_CHANNEL_SECRET=${{secrets.LINE_CHANNEL_SECRET}}
#        export A3RT_TALKAPI_APIKEY=${{secrets.A3RT_TALKAPI_APIKEY}}
#        python -m pip install -r requirements.txt
#        python -m pip install codecov
#        python -m coverage run -m unittest tests/test_core.py
#        codecov

    # codecov/codecov-action
    # https://github.com/codecov/codecov-action
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v1
#      with:
#        token: ${{secrets.CODECOV_TOKEN}}
    # -----

    # AkhileshNS/heroku-deploy
    # https://github.com/AkhileshNS/heroku-deploy
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.4.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
