name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # ----- Setup Python
    # actions/setup-python
    # https://github.com/actions/setup-python
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.5

    - name: Setup Python modules
      run: |
        pip uninstall -r requirements.txt
        make init
    # -----
    # ----- Codecov
    # DONE : Setup Python modules(command coverage,codecov)
    - name: Generate coverage report
      run: |
        export NEWSAPI_APIKEY=${{ secrets.NEWSAPI_APIKEY }}
        export A3RT_TALKAPI_APIKEY=${{ secrets.A3RT_TALKAPI_APIKEY }}
        # option .coveragerc
        # create .coverage
        python -m coverage run -m unittest discover
        # create coverage.xml
        python -m coverage xml

    # codecov/codecov-action
    # https://github.com/codecov/codecov-action
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
    # -----
    # ----- Codacy
    # codacy/codacy-coverage-reporter-action
    # https://github.com/codacy/codacy-coverage-reporter-action
    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@0.2.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./coverage.xml
    # -----
    # ----- Sphinx -> GitHub Pages
    # DONE : Setup Python
    # DONE : Setup Python modules
    - name: Build .rst
      run: |
        cd ./docs
        make html

    # peaceiris/actions-gh-pages
    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
    # -----
    # ----- Heroku
    # AkhileshNS/heroku-deploy
    # https://github.com/AkhileshNS/heroku-deploy
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        branch: "main"
    # -----
